-- Panel rápido del paciente: Citas, Filiación, Presupuestos y Tareas.
-- La API también aplica estos cambios de forma idempotente al iniciar.

ALTER TABLE pacientes
  ADD COLUMN IF NOT EXISTS adicional VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS grupo VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS linea_negocio VARCHAR(100) NULL;

ALTER TABLE citas
  ADD COLUMN IF NOT EXISTS doctor VARCHAR(160) NULL,
  ADD COLUMN IF NOT EXISTS motivo VARCHAR(255) NOT NULL DEFAULT 'Consulta',
  ADD COLUMN IF NOT EXISTS comentario TEXT NULL,
  ADD COLUMN IF NOT EXISTS fin_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE presupuestos
  ADD COLUMN IF NOT EXISTS concepto VARCHAR(255) NOT NULL DEFAULT 'Tratamiento dental',
  ADD COLUMN IF NOT EXISTS observaciones TEXT NULL,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tareas_paciente
  ADD COLUMN IF NOT EXISTS nombre VARCHAR(180) NOT NULL DEFAULT 'Seguimiento',
  ADD COLUMN IF NOT EXISTS descripcion TEXT NULL,
  ADD COLUMN IF NOT EXISTS responsable VARCHAR(160) NULL,
  ADD COLUMN IF NOT EXISTS tipo VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS fecha_envio DATETIME NULL,
  ADD COLUMN IF NOT EXISTS plantilla VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
